# Generated by Django 3.2.4 on 2021-09-10 13:55

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210910_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='actorimage',
            name='thumb',
        ),
        migrations.AddField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(default='', upload_to='actors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actorimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images'),
        ),
    ]
