# Generated by Django 3.2.4 on 2021-09-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210910_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='actorimage',
            name='alt',
        ),
        migrations.AlterField(
            model_name='actorimage',
            name='height',
            field=models.IntegerField(default=992),
        ),
        migrations.AlterField(
            model_name='actorimage',
            name='width',
            field=models.IntegerField(default=1768),
        ),
    ]
