# Generated by Django 3.2.4 on 2021-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210910_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorimage',
            name='local_filename',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
