# Generated by Django 3.2.4 on 2021-09-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_actorimage_local_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorimage',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.actor'),
        ),
    ]
