# Generated by Django 3.2.4 on 2021-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_actorimage_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('local_filepath', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='actorimage',
            name='local_filename',
        ),
    ]
