# Generated by Django 3.2.4 on 2021-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210911_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalImage',
        ),
        migrations.AddField(
            model_name='actorimage',
            name='filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(null=True, upload_to='actors'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
