# Generated by Django 3.2.4 on 2021-09-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210911_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='actorimage',
            name='slug',
        ),
    ]
