# Generated by Django 3.2.4 on 2021-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210911_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
