# Generated by Django 3.2.4 on 2021-09-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_actorimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actorimage',
            options={'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='ActorImageLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(null=True, upload_to='thumb')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(default=1768)),
                ('height', models.IntegerField(default=992)),
                ('filepath', models.CharField(blank=True, max_length=1024, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.actor')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
