# Generated by Django 3.2.4 on 2021-09-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumb',
            field=models.ImageField(null=True, upload_to='thumb'),
        ),
    ]
