# Generated by Django 3.2.4 on 2021-09-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_story_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actorimagelocal',
            name='actor',
        ),
        migrations.AddField(
            model_name='actorimagelocal',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.story'),
        ),
    ]
