# Generated by Django 3.2.4 on 2021-11-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210926_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorimagelocal',
            name='cate',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
