# Generated by Django 3.2.4 on 2021-11-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_actorimagelocal_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorimagelocal',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.actor'),
        ),
    ]
