# Generated by Django 3.2.4 on 2021-12-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_actorimagelocal_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorimagelocal',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
