# Generated by Django 2.2.6 on 2020-07-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
