# Generated by Django 2.2.6 on 2020-07-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_novel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('matcher', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='novel',
            name='actors',
            field=models.ManyToManyField(to='main.Actor'),
        ),
    ]
