# Generated by Django 2.2.6 on 2020-07-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200721_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matcher',
            name='match',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
