# Generated by Django 2.2.6 on 2020-07-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200721_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='matcher',
            name='prefix',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
