# Generated by Django 2.2.6 on 2020-07-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_matcher_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('file', models.FileField(upload_to='images/%Y/%m/%d')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Actor')),
            ],
        ),
    ]
