# Generated by Django 2.2.6 on 2020-07-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Actor'),
        ),
    ]
